# Generated by Django 5.0.1 on 2024-02-10 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('sl_no', models.AutoField(primary_key=True, serialize=False)),
                ('stud_name', models.CharField(max_length=100)),
                ('stud_id', models.CharField(max_length=20, unique=True)),
                ('sport', models.CharField(max_length=50)),
                ('department', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('year', models.IntegerField()),
                ('place', models.CharField(max_length=100)),
                ('player_status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=10)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10)),
                ('position', models.CharField(max_length=50)),
                ('selected_to_university', models.BooleanField(default=False)),
                ('graduation_level', models.CharField(max_length=50)),
            ],
        ),
    ]
