# Generated by Django 5.0.1 on 2024-02-10 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SDMSapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='player',
            name='department',
            field=models.CharField(choices=[('computer_science', 'Computer Science'), ('physics', 'Physics'), ('mathematics', 'Mathematics'), ('statistics', 'Statistics'), ('malayalam', 'Malayalam'), ('history', 'History'), ('zoology', 'Zoology'), ('plantsciece', 'Plantsciece'), ('polymer_chemistry', 'Polymer Chemistry'), ('economics', 'Economics'), ('commerce', 'Commerce'), ('english', 'English')], default=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='player',
            name='position',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='player',
            name='sport',
            field=models.CharField(choices=[('sport', 'sport'), ('kabaddi', 'kabaddi'), ('basketball', 'basketball'), ('handball', 'handball'), ('cricket', 'cricket'), ('football', 'football'), ('ball_batminton', 'ball_batminton'), ('shuttle_batminton', 'shuttle_batminton'), ('wrestling', 'wrestling'), ('judo', 'judo'), ('taekwondo', 'taekwondo'), ('karate', 'karate'), ('Kho-kho', 'kho-kho')], default='Active', max_length=50),
        ),
    ]
