# Generated by Django 5.0.1 on 2024-02-17 16:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SDMSapp', '0002_sport_alter_player_department_alter_player_position_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='player',
            name='sport',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SDMSapp.sport'),
        ),
        migrations.AlterField(
            model_name='sport',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='player',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SDMSapp.department'),
        ),
    ]
