# Generated by Django 5.0.1 on 2024-04-16 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SDMSapp', '0003_alter_department_dept_id_alter_item_item_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programme',
            name='dept',
        ),
    ]
