# Generated by Django 5.0.1 on 2024-04-17 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SDMSapp', '0004_remove_programme_dept'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='id',
        ),
        migrations.AlterField(
            model_name='student',
            name='uty_reg_no',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
